version: '3.7'

services:
  app:
    container_name: frontend
    image: 
    restart: always
    build: ./frontend
    ports: ['8660:8660']
  back:
    # depends_on:
    #   - mongodb
    container_name: backend
    image: 
    restart: always
    build: ./backend
    ports: ['1111:1111']
  
    # environment:
    #   - DB_HOST=mongodb
    #   - DB_USER=admin
    #   - DB_PASSWORD=admin
    #   - DB_NAME=traderrecord
    #   - DB_PORT=27017
    # stdin_open: true
    # tty: true
#   mongodb:
#     image: mongo:5.0.2
#     restart: unless-stopped
    
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=admin
#     ports:
#       - 27017:27017
#     volumes:
#       - db:/data/db
# volumes:
#   db:
